In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import kagglehub

## Data processing

In [3]:
# Download latest version
path = kagglehub.dataset_download("mohamedbakhet/amazon-books-reviews")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\user\.cache\kagglehub\datasets\mohamedbakhet\amazon-books-reviews\versions\1

In [4]:
review_path = path + '\\Books_rating.csv'
book_path = path + '\\books_data.csv'

books = pd.read_csv(book_path)
reviews = pd.read_csv(review_path)

In [5]:
# Merge 2 dataset by the book title
data = pd.merge(reviews, books, on='Title', how='inner')
data.head()

,Id,Title,Price,User_id,profileName,review/helpfulness,review/score,review/time,review/summary,review/text,description,authors,image,previewLink,publisher,publishedDate,infoLink,categories,ratingsCount
0,1882931173,Its Only Art If Its Well Hung!,NaN,AVCGYZL8FQQTD,"Jim of Oz ""jim-of-oz""",7/7,4.0,940636800,Nice collection of Julie Strain images,This is only for Julie Strain fans. It's a col...,NaN,['Julie Strain'],http://books.google.com/books/content?id=DykPA...,http://books.google.nl/books?id=DykPAAAACAAJ&d...,NaN,1996,http://books.google.nl/books?id=DykPAAAACAAJ&d...,['Comics & Graphic Novels'],NaN
1,0826414346,Dr. Seuss: American Icon,NaN,A30TK6U7DNS82R,Kevin Killian,10/10,5.0,1095724800,Really Enjoyed It,I don't care much for Dr. Seuss but after read...,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN
2,0826414346,Dr. Seuss: American Icon,NaN,A3UH4UZ4RSVO82,John Granger,10/11,5.0,1078790400,Essential for every personal and Public Library,"If people become the books they read and if ""t...",Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN
3,0826414346,Dr. Seuss: American Icon,NaN,A2MVUWT453QH61,"Roy E. Perry ""amateur philosopher""",7/7,4.0,1090713600,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D...",Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN
4,0826414346,Dr. Seuss: American Icon,NaN,A22X4XUPKF66MR,"D. H. Richards ""ninthwavestore""",3/3,4.0,1107993600,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,http://books.google.nl/books?id=IjvHQsCn_pgC&p...,A&C Black,2005-01-01,http://books.google.nl/books?id=IjvHQsCn_pgC&d...,['Biography & Autobiography'],NaN

In [6]:
# Drop duplicate rows across all columns
data = data.drop_duplicates()

# Drop rows with missing data in columns: 'image', 'Title' and 5 other columns
data = data.dropna(subset=['image', 'Title', 'description', 'authors', 'User_id', 'review/summary', 'review/text'])

# Filter rows based on column: 'review/time'
data = data[data['review/time'] > 0]

# Drop columns: 'publisher', 'previewLink' and 6 other columns
data = data.drop(columns=['publisher', 'previewLink', 'publishedDate', 'infoLink', 'ratingsCount', 'Price', 'Id', 'profileName'])

data.head()

,Title,User_id,review/helpfulness,review/score,review/time,review/summary,review/text,description,authors,image,categories
1,Dr. Seuss: American Icon,A30TK6U7DNS82R,10/10,5.0,1095724800,Really Enjoyed It,I don't care much for Dr. Seuss but after read...,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,['Biography & Autobiography']
2,Dr. Seuss: American Icon,A3UH4UZ4RSVO82,10/11,5.0,1078790400,Essential for every personal and Public Library,"If people become the books they read and if ""t...",Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,['Biography & Autobiography']
3,Dr. Seuss: American Icon,A2MVUWT453QH61,7/7,4.0,1090713600,Phlip Nel gives silly Seuss a serious treatment,"Theodore Seuss Geisel (1904-1991), aka &quot;D...",Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,['Biography & Autobiography']
4,Dr. Seuss: American Icon,A22X4XUPKF66MR,3/3,4.0,1107993600,Good academic overview,Philip Nel - Dr. Seuss: American IconThis is b...,Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,['Biography & Autobiography']
5,Dr. Seuss: American Icon,A2F6NONFUDB6UK,2/2,4.0,1127174400,One of America's greatest creative talents,"""Dr. Seuss: American Icon"" by Philip Nel is a ...",Philip Nel takes a fascinating look into the k...,['Philip Nel'],http://books.google.com/books/content?id=IjvHQ...,['Biography & Autobiography']

In [7]:
# value counts 
review_counts = data['Title'].value_counts()

# Filter books with less than 10 reviews
filtered_books = review_counts[review_counts >= 20].index
data = data[data['Title'].isin(filtered_books)]

data.shape

(1342482, 11)

In [8]:
# Give each book a unique ID
cur = 0
map = {}
for i in range(len(data)):
    book = data.iloc[i]
    if(book['Title'] not in map):
        map[book['Title']] = cur
        cur += 1

# Add the unique ID to each book
data['Book_id'] = data['Title'].apply(lambda x: map[x])

print("Total number of books:", cur)
data.head()

Total number of books: 14507

,Title,User_id,review/helpfulness,review/score,review/time,review/summary,review/text,description,authors,image,categories,Book_id
14,Whispers of the Wicked Saints,A3Q12RK71N74LB,7/11,1.0,1117065600,not good,I bought this book because I read some glowing...,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,['Fiction'],0
15,Whispers of the Wicked Saints,A1E9M6APK30ZAU,1/2,4.0,1119571200,Here is my opinion,"I have to admit, I am not one to write reviews...",Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,['Fiction'],0
16,Whispers of the Wicked Saints,AUR0VA5H0C66C,1/2,1.0,1119225600,Buyer beware,"This is a self-published book, and if you want...",Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,['Fiction'],0
17,Whispers of the Wicked Saints,A1YLDZ3VHR6QPZ,2/4,5.0,1115942400,Fall on your knee's,When I first read this the I was mezmerized at...,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,['Fiction'],0
18,Whispers of the Wicked Saints,ACO23CG8K8T77,5/9,5.0,1117065600,Bravo Veronica,I read the review directly under mine and I ha...,Julia Thomas finds her life spinning out of co...,['Veronica Haddon'],http://books.google.com/books/content?id=aRSIg...,['Fiction'],0

In [9]:
# filter user who rates less than 10 books
user_rating_count = data.groupby('User_id')['Book_id'].count()
active_users = user_rating_count[user_rating_count >= 10].index
data = data[data['User_id'].isin(active_users)]

data.shape

(403617, 12)

In [10]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 403617 entries, 140 to 2999975
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Title               403617 non-null  object
 1   User_id             403617 non-null  object
 2   review/helpfulness  403617 non-null  object
 3   review/score        403617 non-null  float64
 4   review/time         403617 non-null  int64
 5   review/summary      403617 non-null  object
 6   review/text         403617 non-null  object
 7   description         403617 non-null  object
 8   authors             403617 non-null  object
 9   image               403617 non-null  object
 10  categories          371885 non-null  object
 11  Book_id             403617 non-null  int64
dtypes: float64(1), int64(2), object(9)
memory usage: 40.0+ MB

In [ ]:
import ast

data['categories'] = data['categories'].fillna('Not Provided')

# Parse the categories
def parse(string):
	return ast.literal_eval(string) if string != 'Not Provided' else ['Not Provided']

data['categories'] = data['categories'].apply(parse)

# Calculate the length of each category
length = set()
for category in data['categories']:
    length.add(len(category))
    
print(length)

{1}

In [ ]:
# There's only 1 category for each book
data['categories'] = data['categories'].str[0]

In [25]:
data.head()

,Title,User_id,review/helpfulness,review/score,review/time,review/summary,review/text,description,authors,image,categories,Book_id
140,Eyewitness Travel Guide to Europe,A281NPSIMI1C2R,19/19,5.0,1023235200,The Major Sights in Twenty Countries - Amazing!,"Yes, this is one heavy book. It is more than l...",The DK Eyewitness Travel Guide: Eastern and Ce...,"['Dorling Kindersley Publishing Staff', 'Jonat...",http://books.google.com/books/content?id=h4wor...,Europe,2
141,Eyewitness Travel Guide to Europe,A2TAPL67U2A5HM,12/13,5.0,1111190400,Europe (Eyewitness Travel Guides) by Dan Colwell,Eyewitness travel guides are splendid and this...,The DK Eyewitness Travel Guide: Eastern and Ce...,"['Dorling Kindersley Publishing Staff', 'Jonat...",http://books.google.com/books/content?id=h4wor...,Europe,2
142,Eyewitness Travel Guide to Europe,AT9YSY20RJUDX,11/13,4.0,1033689600,Helpful guide on tours through Europe,I recently took a backpack trip through Europe...,The DK Eyewitness Travel Guide: Eastern and Ce...,"['Dorling Kindersley Publishing Staff', 'Jonat...",http://books.google.com/books/content?id=h4wor...,Europe,2
413,Night World: Daughters Of Darkness,A2KBHSK5BS35BH,0/0,1.0,1260662400,Night World 2: Daughters of Darkness,"Night World #2: Daughters of Darkness, by L. J...","""There’s something strange about the new girls...",['L.J. Smith'],http://books.google.com/books/content?id=c9icD...,Juvenile Fiction,3
450,Night World: Daughters Of Darkness,A2WZON0QPX7C9X,0/0,5.0,964656000,Ash rules!,"I thought this story was amazing, even better ...","""There’s something strange about the new girls...",['L.J. Smith'],http://books.google.com/books/content?id=c9icD...,Juvenile Fiction,3

In [33]:
# Do the same thing for authors
# data['authors'] = data['authors'].apply(parse)

length = set()
for author in data['authors']:
    length.add(len(author))
    
print(length)

{1, 2, 3, 4, 5, 6, 7, 33, 9, 8, 13}

In [22]:
# parse "helpfulness" from string into float 
# "1/2" --> 0.5

def parse_helpfulness(helpfulness_str):
    return eval(helpfulness_str) if helpfulness_str != "0/0" else 0.0

data['review/helpfulness'] = data['review/helpfulness'].apply(parse_helpfulness)
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 403617 entries, 140 to 2999975
Data columns (total 12 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Title               403617 non-null  object
 1   User_id             403617 non-null  object
 2   review/helpfulness  403617 non-null  float64
 3   review/score        403617 non-null  float64
 4   review/time         403617 non-null  int64
 5   review/summary      403617 non-null  object
 6   review/text         403617 non-null  object
 7   description         403617 non-null  object
 8   authors             403617 non-null  object
 9   image               403617 non-null  object
 10  categories          403617 non-null  object
 11  Book_id             403617 non-null  int64
dtypes: float64(2), int64(2), object(8)
memory usage: 48.1+ MB

In [10]:
# Insert data into database : database/reviews.db
import sqlite3

conn = sqlite3.connect('../database/reviews.db')
cur = conn.cursor()

# Insert books data
# Keys: Book_id, Title, Description, Cover
for _, row in data.iterrows():
    book_id = row['Book_id']
    title = row['Title']
    description = row['description']
    cover = row['image']  
    
    # Check if the book already exists, if not insert it
    cur.execute('''
        INSERT OR IGNORE INTO Books (Book_id, Title, Description, Cover)
        VALUES (?, ?, ?, ?)
    ''', (book_id,title, description, cover))
    
# Insert reviews data
# Keys: Review_id (auto), User_id, Book_id, Helpfulness, Score, Time, Summary, Comment
for _, row in data.iterrows():
    user_id = row['User_id']
    book_id = row['Book_id']
    helpfulness = row['review/helpfulness']
    score = row['review/score']
    time = row['review/time']
    summary = row['review/summary']
    comment = row['review/text']
    
	# Check if the review already exists, if not insert it
    cur.execute('''
        INSERT OR IGNORE INTO Reviews (User_id, Book_id, Helpfulness, Score, Time, Summary, Comment)
        VALUES (?, ?, ?, ?, ?, ?, ?)
    ''', (user_id, book_id, helpfulness, score, time, summary, comment))

Index(['Title', 'User_id', 'review/helpfulness', 'review/score', 'review/time',
       'review/summary', 'review/text', 'description', 'authors', 'image',
       'categories', 'Book_id'],
      dtype='object')

## Collabrative Filtering Recommendation System

For user-based collaborative filtering, we need these columns:

- `User_id`: the id of the user

- `Book_id`: the id of the item
- `review/score`: the rating given by the user to the item

In [11]:
collabrative_filtering = pd.DataFrame(
    {
        "UserId": data['User_id'],
        "BookId": data['Book_id'],
        "Rating": data['review/score']
    }
)

collabrative_filtering.head()

             UserId  BookId  Rating
140  A281NPSIMI1C2R       2     5.0
141  A2TAPL67U2A5HM       2     5.0
142   AT9YSY20RJUDX       2     4.0
417  A2KBHSK5BS35BH       3     1.0
454  A2WZON0QPX7C9X       3     5.0

In [12]:
collabrative_filtering.to_csv('data/collaborative_filtering.csv', index=False)